version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: market-ml-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./configs:/app/configs
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: market-ml-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    stdin_open: true
    tty: true
