# Market Intelligence ML Configuration

data:
  start_date: "2018-01-01"
  end_date: "2025-01-01"
  train_end: "2023-12-31"
  val_end: "2024-06-30"
  
assets:
  equities: [SPY, XLK, XLF, XLV, XLE, XLI]
  fixed_income: [TLT, IEF]
  alternatives: [GLD]
  crypto: [BTC/USDT, ETH/USDT, SOL/USDT]
  macro: [^VIX]

features:
  ma_windows: [5, 10, 20, 50, 200]
  rsi_period: 14
  
models:
  xgboost:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.01

backtest:
  transaction_cost: 0.001
  slippage: 0.0005
